[site]
description = 'A blog about software development.'
logo = ''
name = 'Niladic Podcast'
url = 'https://www.niladicpodcast.com/'

[folders]
build = 'build'
pages = 'pages'
posts = 'posts'
static = 'static'
templates = 'templates'

[html]
# How to format HTML
# Only set one to True
# If pretty is true, minify will not be checked
pretty = false
minify = false

[posts]
base_path = '/blog/'
extension = '.md'

[posts.author]
# Show author at the top of every post?
show = true
# Author to use if author is not specified in the post file
default_name = 'Cody'

[posts.comments]
# https://cusdis.com/doc#/advanced/sdk
enabled = true
cusdis_host = 'https://cusdis.com'
cusdis_app_id = '6fe398cd-a881-4122-bea7-ba7f4a832aae'

[posts.discovery]
random_post_enabled = true

[posts.markdown]
extensions = [
    'codehilite',
    'fenced_code',
    'mdx_linkify',
]

[redirects]
'/blog/2016/5/how-to-setup-lets-encrypt-with-nginx/' = '/2016/05/15/how-to-setup-lets-encrypt-with-nginx/'
'/blog/2017/1/whats-the-deal-with-ctrlleft-and-ctrlright/' = '/2017/01/14/whats-the-deal-with-ctrlleft-and-ctrlright/'
'/blog/2017/4/my-problems-with-bitbucket-cloud/' = '/2017/04/19/my-problems-with-bitbucket-cloud/'
'/blog/2018/3/run-linux-gui-applications-on-windows-10/' = '/2018/03/12/run-linux-gui-applications-on-windows-10/'
'/blog/2017/8/install-pyqt5-inside-a-virtual-environment/' = '/2017/08/17/install-pyqt5-inside-a-virtual-environment/'
'/blog/2018/1/setup-a-local-sftp-server-for-development/' = '/2018/01/10/setup-a-local-sftp-server-for-development/'
